CREATE TABLE  "OPENACCOUNT" 
   (	"ACCOUNTNO" NUMBER, 
	"USERNAME" VARCHAR2(4000), 
	"PASSWORD" VARCHAR2(4000), 
	"REPASSWORD" VARCHAR2(4000), 
	"AMOUNT" NUMBER, 
	"ADDRESS" VARCHAR2(4000), 
	"PHONE" NUMBER, 
	 CONSTRAINT "OPENACCOUNT_PK" PRIMARY KEY ("ACCOUNTNO") ENABLE
   )
/


CREATE OR REPLACE TRIGGER  "BI_OPENACCOUNT" 
  before insert on "OPENACCOUNT"               
  for each row  
begin   
    select "OPENACCOUNT_SEQ".nextval into :NEW.ACCOUNTNO from dual; 
end; 

/
ALTER TRIGGER  "BI_OPENACCOUNT" ENABLE
/
CREATE SEQUENCE OPENACCOUNT_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE